sudo: required

services: 
  - docker

env: 
  global:
    - IMAGE_NAME = hoang1712/project-final
    
# before_install:
  

before_script:
  - echo ${REGISTRY_USER}
  - docker login -u hoang1712
  - docker pull ${IMAGE_NAME} || true

script:
  - docker build --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${TRAVIS_COMMIT} .
  - docker push ${IMAGE_NAME}:${TRAVIS_COMMIT}

after_script:
  - docker images

before_deploy: 
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker pull ${IMAGE_NAME}:${TRAVIS_COMMIT}
  - docker tag ${IMAGE_NAME}:${TRAVIS_COMMIT} ${IMAGE_NAME}:latest
  - docker push ${IMAGE_NAME}:latest
  - ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f ./deploy_rsa
  - travis encrypt-file deploy_rsa --add
  - ssh-copy-id -i deploy_rsa.pub hoang171220001@<deploy-host>
  - rm -f deploy_rsa deploy_rsa.pub
  - git add deploy_rsa.enc .travis.yml

deploy: 
  provider: script
  script: docker push ${IMAGE_NAME}:latest
  on:
    branch: main

after_deploy:
  - docker rm -f ${IMAGE_NAME}:${TRAVIS_COMMIT} || true
  - docker images