version: '3.7'

services:
  redis:
    user: ${WHOAMI}
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis
    environment:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./config/docker/1.redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/persistence:/var/redis/6379
      - ./data/redis/run:/var/run
    networks:
      - template_network

  mongo:
    image: mongo
    # environment:                      
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - template_network
    # volumes:
    #   - ./data/mongo:/data/db
    restart: always

networks:
  template_network:
    name: ${NETWORK_NAME}
